version: '3.9'

services:
  client-dev:
    build:
      context: .
      target: development
    container_name: inputly-client-dev
    ports:
      - '5173:5173'  # Vite dev server port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    command: npm run dev

  client-prod:
    build:
      context: .
      target: production
    container_name: inputly-client-prod
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production