apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
