apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Values.metrics.prometheusRelease | default "kube-prometheus-stack" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
